sed -E -i '' 's/\\section{([^}]*)}/---\ntitle: \1\nlayout: default\n---/g' "$1"
sed -E -i '' 's/\\begin{solution}/{% solution %}/g' "$1"
sed -E -i '' 's/\\end{solution}/{% endsolution %}/g' "$1"
sed -E -i '' 's/\\begin{equation.?}/$/g' "$1"
sed -E -i '' 's/\\end{equation.?}/$/g' "$1"
sed -E -i '' 's/\\begin{align.?}/__BEGIN_ALIGN__/g' "$1"
sed -E -i '' 's/\\end{align.?}/__END_ALIGN__/g' "$1"
sed -E -i '' 's/\\end{solution}/{% endsolution %}/g' "$1"
sed -E -i '' 's/\\end{([^}]*)}//g' "$1"
sed -E -i '' 's/\\begin{([^}]*)}//g' "$1"
sed -E -i '' 's/__BEGIN_ALIGN__/$\n\\begin{align}/g' "$1"
sed -E -i '' 's/__END_ALIGN__/\\end{align}\n$/g' "$1"
sed -E -i '' 's/\\newline//g' "$1"
sed -E -i '' 's/\\subsubsection\*{([^}]*)}/### \1/g' "$1"
sed -E -i '' 's/\\subsection\*{([^}]*)}/### \1/g' "$1"
sed -E -i '' 's/\\subsection{([^}]*)}/## \1/g' "$1"
sed -E -i '' 's/\\texttt{([^}]*)}/`\1`/g' "$1"
sed -E -i '' 's/\\textbf{([^}]*)}/**\1**/g' "$1"
sed -E -i '' "s/\\\\includegraphics\[scale=1\]{([^}]*)}/![]({{'\1' | relative_url}})/g" "$1"
sed -E -i '' 's/\[!h\]//g' "$1"
sed -E -i '' 's/\\caption.*//' "$1"
sed -E -i '' 's/\\centering//g' "$1"
sed -E -i '' 's/\\subfigure{}{//g' "$1"
sed -E -i '' 's/\\hspace{[^}]*}//g' "$1"
sed -E -i '' 's/^}//' "$1"
sed -E -i '' 's/\$/$$/g' "$1"
sed -E -i '' 's/\\item/*/g' "$1"
sed -E -i '' 's/``/"/g' "$1"
sed -E -i '' "s/''/\"/g" "$1"